- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - generic [ref=e3]:
      - banner [ref=e4]:
        - navigation [ref=e5]:
          - generic [ref=e6]:
            - link "MacroMicro 財經M平方" [ref=e7] [cursor=pointer]:
              - /url: javascript:;
            - generic [ref=e8]:
              - generic [ref=e9]:
                - button " 搜尋..." [ref=e10] [cursor=pointer]:
                  - generic [ref=e11]: 
                  - generic [ref=e12]: 搜尋...
                - text:  
              - link "立即訂閱" [ref=e13] [cursor=pointer]:
                - /url: /subscribe#individual
                - generic [ref=e14]: 立即訂閱
              - text: 
              - button "" [ref=e16] [cursor=pointer]:
                - generic [ref=e17]: 
              - link "登入" [ref=e18] [cursor=pointer]:
                - /url: /login?next=%2F
                - generic [ref=e19]: 登入
              - text:         
              - button " Menu" [ref=e20] [cursor=pointer]:
                - generic [ref=e21]: 
                - generic [ref=e22]: Menu
            - list [ref=e24]:
              - listitem [ref=e25]:
                - button "總經" [ref=e26] [cursor=pointer]
              - listitem [ref=e27]:
                - button "圖表" [ref=e28] [cursor=pointer]
                - text: 
              - listitem [ref=e29]:
                - button "專區" [ref=e30] [cursor=pointer]
                - text:           
              - listitem [ref=e31]:
                - button "行情" [ref=e32] [cursor=pointer]
                - text:        
              - listitem [ref=e33]:
                - button "分析" [ref=e34] [cursor=pointer]
                - text:    
              - text:   
              - listitem [ref=e35]:
                - button "學院" [ref=e36] [cursor=pointer]
                - text:   
              - text:                    
      - main [ref=e37]:
        - generic [ref=e39]:
          - generic [ref=e41]:
            - link [ref=e45] [cursor=pointer]:
              - /url: https://www.macromicro.me/mails/monthly_report
              - generic [ref=e46]:
                - heading [level=1]
                - heading [level=2]
            - generic [ref=e48]:
              - img "科技新冷戰：" [ref=e50]
              - link "科技新冷戰： 美中 AI 競爭力深度診斷報告！ 解鎖訂閱報告" [ref=e51] [cursor=pointer]:
                - /url: https://www.macromicro.me/blog/market-update-a-new-cold-war-in-technology-indepth-diagnostic-report-on-uschina-ai-competitiveness
                - generic [ref=e52]:
                  - heading "科技新冷戰：" [level=1] [ref=e53]
                  - heading "美中 AI 競爭力深度診斷報告！ 解鎖訂閱報告" [level=2] [ref=e54]:
                    - text: 美中 AI 競爭力深度診斷報告！
                    - generic [ref=e55]: 解鎖訂閱報告
            - link [ref=e59] [cursor=pointer]:
              - /url: https://www.macromicro.me/video/547/2026-global-economic-outlook-package-thematic-trends-special-fully-online-livestream
              - generic [ref=e60]:
                - heading [level=1]
                - heading [level=2]
            - generic [ref=e62]:
              - img "中東戰火下資產重定價" [ref=e64]
              - link "中東戰火下資產重定價 股債已達關鍵水位！ 解鎖訂閱報告" [ref=e65] [cursor=pointer]:
                - /url: https://www.macromicro.me/blog/market-update-asset-repricing-amid-middle-east-conflict-stocks-and-bonds-have-reached-critical-levels
                - generic [ref=e66]:
                  - heading "中東戰火下資產重定價" [level=1] [ref=e67]
                  - heading "股債已達關鍵水位！ 解鎖訂閱報告" [level=2] [ref=e68]:
                    - text: 股債已達關鍵水位！
                    - generic [ref=e69]: 解鎖訂閱報告
            - link [ref=e73] [cursor=pointer]:
              - /url: https://www.macromicro.me/mails/monthly_report
              - generic [ref=e74]:
                - heading [level=1]
                - heading [level=2]
            - generic [ref=e76]:
              - img "科技新冷戰：" [ref=e78]
              - link "科技新冷戰： 美中 AI 競爭力深度診斷報告！ 解鎖訂閱報告" [ref=e79] [cursor=pointer]:
                - /url: https://www.macromicro.me/blog/market-update-a-new-cold-war-in-technology-indepth-diagnostic-report-on-uschina-ai-competitiveness
                - generic [ref=e80]:
                  - heading "科技新冷戰：" [level=1] [ref=e81]
                  - heading "美中 AI 競爭力深度診斷報告！ 解鎖訂閱報告" [level=2] [ref=e82]:
                    - text: 美中 AI 競爭力深度診斷報告！
                    - generic [ref=e83]: 解鎖訂閱報告
            - link [ref=e87] [cursor=pointer]:
              - /url: https://www.macromicro.me/video/547/2026-global-economic-outlook-package-thematic-trends-special-fully-online-livestream
              - generic [ref=e88]:
                - heading [level=1]
                - heading [level=2]
            - generic [ref=e90]:
              - img "中東戰火下資產重定價" [ref=e92]
              - link "中東戰火下資產重定價 股債已達關鍵水位！ 解鎖訂閱報告" [ref=e93] [cursor=pointer]:
                - /url: https://www.macromicro.me/blog/market-update-asset-repricing-amid-middle-east-conflict-stocks-and-bonds-have-reached-critical-levels
                - generic [ref=e94]:
                  - heading "中東戰火下資產重定價" [level=1] [ref=e95]
                  - heading "股債已達關鍵水位！ 解鎖訂閱報告" [level=2] [ref=e96]:
                    - text: 股債已達關鍵水位！
                    - generic [ref=e97]: 解鎖訂閱報告
          - generic [ref=e98]:
            - button [ref=e99] [cursor=pointer]
            - button [ref=e101] [cursor=pointer]
            - button [ref=e103] [cursor=pointer]
            - button [ref=e105] [cursor=pointer]
        - generic [ref=e109]:
          - generic [ref=e110]:
            - heading "最專業的全球總經投資平台" [level=3] [ref=e111]
            - paragraph [ref=e112]: MacroMicro 透過金融結合科技，告訴你如何運用數據，快速掌握全球金融趨勢！
            - iframe [ref=e114]:
              - generic [active] [ref=f11e1]:
                - generic "YouTube 影片播放器" [ref=f11e3]
                - generic [ref=f11e5]:
                  - generic:
                    - generic:
                      - button "播放影片" [ref=f11e10] [cursor=pointer]:
                        - generic [ref=f11e13]:
                          - img
                      - button "隱藏播放器控制項" [ref=f11e14] [cursor=pointer]
                      - generic [ref=f11e16]:
                        - generic [ref=f11e21]:
                          - generic [ref=f11e22]:
                            - link "財經M平方 Macromicro | 讓投資人輕鬆掌握的總經數據的分析平台" [ref=f11e23] [cursor=pointer]:
                              - /url: https://www.youtube.com/watch?v=RbzMwaQ7PgI
                            - link "MacroMicro財經M平方" [ref=f11e24] [cursor=pointer]:
                              - /url: /channel/UC6LU7FUBvbFCh_cQasrHZ_Q
                              - generic [ref=f11e25]: MacroMicro財經M平方
                          - generic [ref=f11e26]:
                            - button "thumbnail-image" [ref=f11e27] [cursor=pointer]:
                              - img "thumbnail-image" [ref=f11e28]
                            - generic [ref=f11e30]:
                              - generic: MacroMicro財經M平方
                              - generic: 6.19萬位訂閱者
                        - generic [ref=f11e31]:
                          - button "分享" [ref=f11e34] [cursor=pointer]:
                            - generic [ref=f11e38]:
                              - img
                          - link "在 YouTube 上觀看" [ref=f11e45] [cursor=pointer]:
                            - /url: https://www.youtube.com/watch?v=RbzMwaQ7PgI
                            - generic [ref=f11e48]:
                              - text: 觀看平台：
                              - img [ref=f11e50]:
                                - generic [ref=f11e52]:
                                  - img
          - generic [ref=e115]:
            - generic [ref=e116]:
              - generic [ref=e117]:
                - text: 0萬+
                - heading "全球總會員數" [level=5] [ref=e118]
              - generic [ref=e119]:
                - text: 0萬+
                - heading "總圖表數" [level=5] [ref=e120]
              - generic [ref=e121]:
                - text: 0萬+
                - heading "年度造訪流量" [level=5] [ref=e122]
            - separator [ref=e123]
          - generic [ref=e124]:
            - heading "讓 MacroMicro 成為你的最佳策略夥伴！" [level=3] [ref=e125]
            - paragraph [ref=e126]: 從數據與圖表出發，一起重視基本面，為自己的投資負責！
            - link "馬上成為訂閱會員" [ref=e127] [cursor=pointer]:
              - /url: /subscribe
              - generic [ref=e128]: 馬上成為訂閱會員
        - generic [ref=e132]:
          - heading "所有投資決策的核心，都在確認市場目前處在的位置" [level=3] [ref=e133]
          - paragraph [ref=e134]: 我們相信景氣會一次次循環，秉持「循環為主、數據為輔」的洞悉方法，運用數據做出投資決策。
          - link "挖掘更多投資的蛛絲馬跡" [ref=e135] [cursor=pointer]:
            - /url: /macro
            - img "挖掘更多投資的蛛絲馬跡" [ref=e136]
        - generic [ref=e140]:
          - heading "讓數據說話，動態追蹤全球趨勢" [level=3] [ref=e141]
          - paragraph [ref=e142]: 我們從眾多數據中抽絲剝繭，並以直覺式的圖表呈現趨勢洞見，幫助你有效率地規劃投資想法。
          - generic [ref=e144]:
            - generic [ref=e146]:
              - generic [ref=e148]:
                - img "MM全球景氣衰退機率" [ref=e151]:
                  - generic [ref=e165]: Percent
                  - generic [ref=e170]: MM全球景氣衰退機率
                  - generic [ref=e176] [cursor=pointer]: MM全球景氣衰退機率
                  - generic [ref=e177]:
                    - generic [ref=e178]: "1990"
                    - generic [ref=e179]: "2000"
                    - generic [ref=e180]: "2010"
                    - generic [ref=e181]: "2020"
                  - generic [ref=e182]:
                    - generic [ref=e183]: "0"
                    - generic [ref=e184]: "20"
                    - generic [ref=e185]: "40"
                    - generic [ref=e186]: "60"
                    - generic [ref=e187]: "80"
                    - generic [ref=e188]: "100"
                - generic [ref=e189]:
                  - generic [ref=e190]:
                    - text: M平方根據各項世界經濟指標編製 MM 全球景氣衰退機率，指標包含了消費、就業、生產製造、金融和原物料等多...
                    - link "看更多" [ref=e191] [cursor=pointer]:
                      - /url: https://www.macromicro.me/charts/7898/mm-global-economic-recession-rate
                  - generic [ref=e194] [cursor=pointer]: 
              - generic [ref=e198]:
                - generic [ref=e199]:
                  - text: 由於全球化下工業分工明確，我們可以藉由中國、台灣及美國三者的新訂單減客戶庫存判斷製造業循環的階段。...
                  - link "看更多" [ref=e200] [cursor=pointer]:
                    - /url: https://www.macromicro.me/charts/37001/manufacturing-cycle-new-orders-minus-customer-inventory
                - generic [ref=e203] [cursor=pointer]: 
              - generic [ref=e207]:
                - generic [ref=e208]:
                  - text: 全球央行淨降息比例計算方法 = 有多少比例的央行「最後一次利率調整為降息」- 有多少比例的央行「最後一次...
                  - link "看更多" [ref=e209] [cursor=pointer]:
                    - /url: https://www.macromicro.me/charts/50290/net-pct-of-cbs-last-move-was-a-rate-cut
                - generic [ref=e212] [cursor=pointer]: 
              - generic [ref=e216]:
                - generic [ref=e217]:
                  - text: 財經M平方運用 OpenAI 的 Embedding 技術所計算出的 MM AI 聯準會聲明稿鷹鴿與樂觀指數，鷹鴿指數數值越大...
                  - link "看更多" [ref=e218] [cursor=pointer]:
                    - /url: https://www.macromicro.me/charts/80611/us-mm-fed-statement-hawkish-dovish-and-optimistic-index
                - generic [ref=e221] [cursor=pointer]: 
              - generic [ref=e225]:
                - generic [ref=e226]:
                  - text: ▌這張圖為何重要？ 『預期』是影響市場重要因子，除了基本面的走勢外，M平方創辦人也常提到，行情 = 資金 +...
                  - link "看更多" [ref=e227] [cursor=pointer]:
                    - /url: https://www.macromicro.me/charts/81110/global-macromicro-economic-index
                - generic [ref=e230] [cursor=pointer]: 
            - generic:
              - button "" [ref=e231]:
                - generic [ref=e232]: 
              - button "" [ref=e233] [cursor=pointer]:
                - generic [ref=e234]: 
            - generic [ref=e235]:
              - button [ref=e236] [cursor=pointer]
              - button [ref=e238] [cursor=pointer]
              - button [ref=e240] [cursor=pointer]
              - button [ref=e242] [cursor=pointer]
              - button [ref=e244] [cursor=pointer]
          - link "立即探索圖表" [ref=e246] [cursor=pointer]:
            - /url: /trader-insights
            - generic [ref=e247]: 立即探索圖表
        - generic [ref=e249]:
          - generic [ref=e250]:
            - heading "一站式體驗為您規劃的海量服務" [level=3] [ref=e251]
            - paragraph [ref=e252]: 從這個頁面開始，你將會透過下面的服務，完整理解全球經濟運行，加入我們的行列吧！
          - generic [ref=e255]:
            - generic [ref=e256]:
              - link "挖掘更多投資的蛛絲馬跡" [ref=e257] [cursor=pointer]:
                - /url: /collections/34/us-stock-relative/402/us-optimus-prime-index-gspc
                - img "挖掘更多投資的蛛絲馬跡" [ref=e258]
              - heading "動態圖表，自動化呈現投資趨勢" [level=5] [ref=e259]:
                - link "動態圖表，自動化呈現投資趨勢" [ref=e260] [cursor=pointer]:
                  - /url: /collections/34/us-stock-relative/402/us-optimus-prime-index-gspc
              - text: 過去40年「美國-重型卡車銷售量」領先S&P 500反轉超過一年，更多數據與圖表，將大幅提升你的決策效率！
            - generic [ref=e261]:
              - link "研究工具箱：回測工具" [ref=e262] [cursor=pointer]:
                - /url: /toolbox/chart-builder
                - img "研究工具箱：回測工具" [ref=e263]
              - heading "研究工具箱，發現更多新的趨勢" [level=5] [ref=e264]:
                - link "研究工具箱，發現更多新的趨勢" [ref=e265] [cursor=pointer]:
                  - /url: /toolbox/chart-builder
              - text: 提供數據庫使用權，畫出你的趨勢觀點，加入不同的指標、運算個人策略， 創造個人投資地圖。
          - generic [ref=e268]:
            - generic [ref=e269]:
              - link "快速了解商品基本面" [ref=e270] [cursor=pointer]:
                - /url: /video
                - img "快速了解商品基本面" [ref=e271]
              - heading "總經線上學院，持續提升知識視野" [level=5] [ref=e272]:
                - link "總經線上學院，持續提升知識視野" [ref=e273] [cursor=pointer]:
                  - /url: /video
              - text: 相信經濟運行是每個人的必修課，透過影音課程、直播及 Podcast，持續學習、每天進步，落實為自己的投資負責。
            - generic [ref=e274]:
              - link "研究工具箱：回測工具" [ref=e275] [cursor=pointer]:
                - /url: /shared_chart
                - img "研究工具箱：回測工具" [ref=e276]
              - heading "專業總經社群，匯集眾多觀點指標！" [level=5] [ref=e277]:
                - link "專業總經社群，匯集眾多觀點指標！" [ref=e278] [cursor=pointer]:
                  - /url: /shared_chart
              - text: 你還能與其他用戶分享圖表成果，同時蒐集M幣回饋，專業投資社群的迷人之處就在於此！
        - generic [ref=e282]:
          - heading "MM獨家報告" [level=3] [ref=e283]
          - generic [ref=e284]:
            - generic [ref=e285]:
              - paragraph [ref=e287]:
                - time [ref=e288]: 5 Apr 2026
              - heading "【MM一週盤前】地緣風險創 25 年新高，油價站上 110 大關" [level=5] [ref=e289]:
                - link "【MM一週盤前】地緣風險創 25 年新高，油價站上 110 大關" [ref=e290] [cursor=pointer]:
                  - /url: /blog/mm-weekly-premarket-update-geopolitical-risks-hit-a-25year-high-oil-prices-surpass-110
              - paragraph [ref=e291]: 【 MM 一週盤前】市場拒買單川普對伊朗戰爭演說，WTI 油價衝破 110 美元大關，美伊停火時間仍遙遙無期！同...
            - generic [ref=e292]:
              - paragraph [ref=e294]:
                - time [ref=e295]: 31 Mar 2026
              - heading "【行情快報】中東戰火下資產重定價，股債已達關鍵水位！" [level=5] [ref=e296]:
                - link "【行情快報】中東戰火下資產重定價，股債已達關鍵水位！" [ref=e297] [cursor=pointer]:
                  - /url: /blog/market-update-asset-repricing-amid-middle-east-conflict-stocks-and-bonds-have-reached-critical-levels
              - paragraph [ref=e298]: 我們想讓你知道的是： 上週，儘管川普表示談判已取得進展，但荷姆茲海峽實際通行仍近乎中斷，美以聯軍軍事...
            - generic [ref=e299]:
              - paragraph [ref=e301]:
                - time [ref=e302]: 29 Mar 2026
              - heading "【MM一週盤前】美伊談判訊號反覆、油價高檔、記憶體股重挫！" [level=5] [ref=e303]:
                - link "【MM一週盤前】美伊談判訊號反覆、油價高檔、記憶體股重挫！" [ref=e304] [cursor=pointer]:
                  - /url: /blog/mm-weekly-premarket-update-us-signals-negotiations-rebuffed-by-iran-oil-prices-fluctuate-at-high-levels
              - paragraph [ref=e305]: 【 MM 一週盤前】川普於上週一釋放談判訊號，伊朗卻表示雙方未有直接接觸、態度反覆，油價短暫回落後再度...
          - link "立即瀏覽所有報告" [ref=e306] [cursor=pointer]:
            - /url: /blog
            - generic [ref=e307]: 立即瀏覽所有報告
        - generic [ref=e311]:
          - heading "感謝每位支持 MM 的用戶" [level=3] [ref=e312]
          - generic [ref=e313]:
            - generic [ref=e315]:
              - generic [ref=e317]:
                - generic [ref=e319]: 簡
                - generic [ref=e320]:
                  - paragraph [ref=e321]: 你們的團隊太強了!報告一出來，現在媒體就刊出來Fed也開始關心流動性的問題，這就是我覺得你們報告物超所值的地方!
                  - generic [ref=e322]: 簡先生
              - generic [ref=e324]:
                - generic [ref=e326]: C
                - generic [ref=e327]:
                  - paragraph [ref=e328]: 謝謝你們的初衷並持續努力，讓使用者有個靜下來思考並釐清問題的平台！
                  - generic [ref=e329]: Chihying
              - generic [ref=e331]:
                - generic [ref=e333]: "N"
                - generic [ref=e334]:
                  - paragraph [ref=e335]: Thank Rachel and your team for all the hard work you have done. We really appreciate it by using your platform and knowing the economic situation and the global investment environments. Very much appreciated.
                  - generic [ref=e336]: 線上課程問卷回饋
              - generic [ref=e338]:
                - generic [ref=e340]: H
                - generic [ref=e341]:
                  - paragraph [ref=e342]: 這是第四次參加，每年都感受到你們的進步和心血的投入，場地的擴大，場次的增加，不變的是創辦人Rachel的實力及魅力，請繼續加油!!!你們很棒，另外請問MM PRO可以買T-Shirt嗎?
                  - generic [ref=e343]: halulee
              - generic [ref=e345]:
                - generic [ref=e347]: W
                - generic [ref=e348]:
                  - paragraph [ref=e349]: 時間軸的設計真的很好，也有效鑑往知來。
                  - generic [ref=e350]: 18年問卷回饋
              - generic [ref=e352]:
                - generic [ref=e354]: L
                - generic [ref=e355]:
                  - paragraph [ref=e356]: 從各國經濟體質所精心挑選出來的指標，再導到不同金融商品。 對原始數據、甚至大數據的處理精闢，在投資上有極大幫助。
                  - generic [ref=e357]: Mr. Lin (化工業)
              - generic [ref=e359]:
                - generic [ref=e361]: 施
                - generic [ref=e362]:
                  - paragraph [ref=e363]: 專業的內容，闡述平易近人，很用心的內容，有你們真好
                  - generic [ref=e364]: Mr. 施
              - generic [ref=e366]:
                - generic [ref=e368]: R
                - generic [ref=e369]:
                  - paragraph [ref=e370]: 還記得剛使用M平方時，就覺得竟然有一個可以查詢總經的台灣網站，而且把數據都整理得這麼好！印象中那時候M平方好像還沒現在那麼多人使用，不過卻已經讓我印象深刻了，經過這一段時間M平方團隊的努力，我只能說這錢花得太值得了，太太屌了，這個網站！！
                  - generic [ref=e371]: Rebel TU
              - generic [ref=e373]:
                - generic [ref=e375]: 吳
                - generic [ref=e376]:
                  - paragraph [ref=e377]: 謝謝M平方將大量實用的數據視覺化，最常使用"大額交易人持倉"等功能，喜歡新增的"時間軸"功能，可以更完整了解經濟事件的影響。
                  - generic [ref=e378]: 吳小姐
              - generic [ref=e380]:
                - generic [ref=e382]: 王
                - generic [ref=e383]:
                  - paragraph [ref=e384]: 有幫助。 提供很好對現在經濟現處位置的建議。 各大經濟體的剖析，以及對未來要怎麼去針對數據做反應，真的跟我們在治療病人有點相似呢XD
                  - generic [ref=e385]: 王先生
              - generic [ref=e387]:
                - generic [ref=e389]: 蔡
                - generic [ref=e390]:
                  - paragraph [ref=e391]: 今天的分享在 2020 年總經和事件的疏理上，讓我更深入了解到今年投資的標的資產上行的原因，尤其在央行未來貨幣政策工具上的運用，讓我懂了為什麼這幾年各國央行積極研究數字貨幣，這個部分，我也會持續關注。 對未來的投資規劃覺得很有幫助，透過這些圖表的追蹤，避免自己又陷於只追求點位的短線交易，而能更與總經連結以做投資，此外，在 TW 的電子出口年增率上的圖表，更是再次提醒我在 15 單元的總經課程中的所得！
                  - generic [ref=e392]: 蔡小姐
              - generic [ref=e394]:
                - generic [ref=e396]: 黃
                - generic [ref=e397]:
                  - paragraph [ref=e398]: 從全球不同經濟體的各個角度，鉅細靡遺、清楚地介紹，讓我們能從更宏觀的視野來理解，收穫良多，謝謝Ｍ平方。
                  - generic [ref=e399]: 黃先生
              - generic [ref=e401]:
                - generic [ref=e403]: V
                - generic [ref=e404]:
                  - paragraph [ref=e405]: M平方的所有人員，謝謝您們~ 自從上一次的原油戰略分析後，澳幣分析又再一次震撼我。很幸運可以在很混亂的金融環境裡遇到一個永遠理性的M平方,昨晚看完後，突然覺得自己好像基金公司大客戶一樣，雖然還沒賺到錢,但是還是感到既開心又興奮，怎麼說呢，我想最好的感謝做法，應該就是變成M平方的終身會員,不斷跟隨M平方學習、成長，再一次的感謝！
                  - generic [ref=e406]: vivian
              - generic [ref=e408]:
                - generic [ref=e410]: S
                - generic [ref=e411]:
                  - paragraph [ref=e412]: M 平方真的由 Macro 走向 Micro（總經結合到各個產業延伸到單一公司) 最新上檔結合隱大的課程，只有 M 平方能超越 M 平方，也是愛大唯一推薦台灣總經研究的平台，希望繼續陪伴著我們再走下幾個 7 年!!
                  - generic [ref=e413]: David Su
              - generic [ref=e415]:
                - generic [ref=e417]: 任
                - generic [ref=e418]:
                  - paragraph [ref=e419]: 很有幫助。 每次分享會都非常精彩，這次 Rachel 也是帶大家回顧今年全球景氣循環的歷程，並且展望未來，指出行情觀察的關鍵。 這幾年真的從Ｍ平方學到許多實用的投資知識，非常感謝Ｍ平方團隊們，還有專業的用戶分享。
                  - generic [ref=e420]: 任先生
              - generic [ref=e422]:
                - generic [ref=e424]: 簡
                - generic [ref=e425]:
                  - paragraph [ref=e426]: 你們的團隊太強了!報告一出來，現在媒體就刊出來Fed也開始關心流動性的問題，這就是我覺得你們報告物超所值的地方!
                  - generic [ref=e427]: 簡先生
              - generic [ref=e429]:
                - generic [ref=e431]: C
                - generic [ref=e432]:
                  - paragraph [ref=e433]: 謝謝你們的初衷並持續努力，讓使用者有個靜下來思考並釐清問題的平台！
                  - generic [ref=e434]: Chihying
              - generic [ref=e436]:
                - generic [ref=e438]: "N"
                - generic [ref=e439]:
                  - paragraph [ref=e440]: Thank Rachel and your team for all the hard work you have done. We really appreciate it by using your platform and knowing the economic situation and the global investment environments. Very much appreciated.
                  - generic [ref=e441]: 線上課程問卷回饋
              - generic [ref=e443]:
                - generic [ref=e445]: H
                - generic [ref=e446]:
                  - paragraph [ref=e447]: 這是第四次參加，每年都感受到你們的進步和心血的投入，場地的擴大，場次的增加，不變的是創辦人Rachel的實力及魅力，請繼續加油!!!你們很棒，另外請問MM PRO可以買T-Shirt嗎?
                  - generic [ref=e448]: halulee
              - generic [ref=e450]:
                - generic [ref=e452]: W
                - generic [ref=e453]:
                  - paragraph [ref=e454]: 時間軸的設計真的很好，也有效鑑往知來。
                  - generic [ref=e455]: 18年問卷回饋
              - generic [ref=e457]:
                - generic [ref=e459]: L
                - generic [ref=e460]:
                  - paragraph [ref=e461]: 從各國經濟體質所精心挑選出來的指標，再導到不同金融商品。 對原始數據、甚至大數據的處理精闢，在投資上有極大幫助。
                  - generic [ref=e462]: Mr. Lin (化工業)
              - generic [ref=e464]:
                - generic [ref=e466]: 施
                - generic [ref=e467]:
                  - paragraph [ref=e468]: 專業的內容，闡述平易近人，很用心的內容，有你們真好
                  - generic [ref=e469]: Mr. 施
              - generic [ref=e471]:
                - generic [ref=e473]: R
                - generic [ref=e474]:
                  - paragraph [ref=e475]: 還記得剛使用M平方時，就覺得竟然有一個可以查詢總經的台灣網站，而且把數據都整理得這麼好！印象中那時候M平方好像還沒現在那麼多人使用，不過卻已經讓我印象深刻了，經過這一段時間M平方團隊的努力，我只能說這錢花得太值得了，太太屌了，這個網站！！
                  - generic [ref=e476]: Rebel TU
              - generic [ref=e478]:
                - generic [ref=e480]: 吳
                - generic [ref=e481]:
                  - paragraph [ref=e482]: 謝謝M平方將大量實用的數據視覺化，最常使用"大額交易人持倉"等功能，喜歡新增的"時間軸"功能，可以更完整了解經濟事件的影響。
                  - generic [ref=e483]: 吳小姐
              - generic [ref=e485]:
                - generic [ref=e487]: 王
                - generic [ref=e488]:
                  - paragraph [ref=e489]: 有幫助。 提供很好對現在經濟現處位置的建議。 各大經濟體的剖析，以及對未來要怎麼去針對數據做反應，真的跟我們在治療病人有點相似呢XD
                  - generic [ref=e490]: 王先生
              - generic [ref=e492]:
                - generic [ref=e494]: 蔡
                - generic [ref=e495]:
                  - paragraph [ref=e496]: 今天的分享在 2020 年總經和事件的疏理上，讓我更深入了解到今年投資的標的資產上行的原因，尤其在央行未來貨幣政策工具上的運用，讓我懂了為什麼這幾年各國央行積極研究數字貨幣，這個部分，我也會持續關注。 對未來的投資規劃覺得很有幫助，透過這些圖表的追蹤，避免自己又陷於只追求點位的短線交易，而能更與總經連結以做投資，此外，在 TW 的電子出口年增率上的圖表，更是再次提醒我在 15 單元的總經課程中的所得！
                  - generic [ref=e497]: 蔡小姐
              - generic [ref=e499]:
                - generic [ref=e501]: 黃
                - generic [ref=e502]:
                  - paragraph [ref=e503]: 從全球不同經濟體的各個角度，鉅細靡遺、清楚地介紹，讓我們能從更宏觀的視野來理解，收穫良多，謝謝Ｍ平方。
                  - generic [ref=e504]: 黃先生
              - generic [ref=e506]:
                - generic [ref=e508]: V
                - generic [ref=e509]:
                  - paragraph [ref=e510]: M平方的所有人員，謝謝您們~ 自從上一次的原油戰略分析後，澳幣分析又再一次震撼我。很幸運可以在很混亂的金融環境裡遇到一個永遠理性的M平方,昨晚看完後，突然覺得自己好像基金公司大客戶一樣，雖然還沒賺到錢,但是還是感到既開心又興奮，怎麼說呢，我想最好的感謝做法，應該就是變成M平方的終身會員,不斷跟隨M平方學習、成長，再一次的感謝！
                  - generic [ref=e511]: vivian
              - generic [ref=e513]:
                - generic [ref=e515]: S
                - generic [ref=e516]:
                  - paragraph [ref=e517]: M 平方真的由 Macro 走向 Micro（總經結合到各個產業延伸到單一公司) 最新上檔結合隱大的課程，只有 M 平方能超越 M 平方，也是愛大唯一推薦台灣總經研究的平台，希望繼續陪伴著我們再走下幾個 7 年!!
                  - generic [ref=e518]: David Su
              - generic [ref=e520]:
                - generic [ref=e522]: 任
                - generic [ref=e523]:
                  - paragraph [ref=e524]: 很有幫助。 每次分享會都非常精彩，這次 Rachel 也是帶大家回顧今年全球景氣循環的歷程，並且展望未來，指出行情觀察的關鍵。 這幾年真的從Ｍ平方學到許多實用的投資知識，非常感謝Ｍ平方團隊們，還有專業的用戶分享。
                  - generic [ref=e525]: 任先生
              - generic [ref=e527]:
                - generic [ref=e529]: 簡
                - generic [ref=e530]:
                  - paragraph [ref=e531]: 你們的團隊太強了!報告一出來，現在媒體就刊出來Fed也開始關心流動性的問題，這就是我覺得你們報告物超所值的地方!
                  - generic [ref=e532]: 簡先生
            - generic:
              - button "" [ref=e533] [cursor=pointer]:
                - generic [ref=e534]: 
              - button "" [ref=e535] [cursor=pointer]:
                - generic [ref=e536]: 
        - generic [ref=e540]:
          - heading "合作夥伴" [level=3] [ref=e541]
          - generic [ref=e542]:
            - img "cisco" [ref=e544]
            - img "群益期貨" [ref=e546]
            - img "統一證券" [ref=e548]
            - img "凱基證券" [ref=e550]
            - img "Cathay Financial | 國泰世華銀行" [ref=e552]
            - img "金融研訓院" [ref=e554]
            - img "AUO友達光電" [ref=e556]
            - img "hahow | 好學校" [ref=e558]
            - img "遠見" [ref=e560]
      - contentinfo [ref=e561]:
        - link "成為訂閱會員" [ref=e563] [cursor=pointer]:
          - /url: /subscribe
          - generic [ref=e564]: 成為訂閱會員
        - generic [ref=e565]:
          - navigation [ref=e566]:
            - generic [ref=e567]:
              - heading "總經" [level=6] [ref=e568]
              - list [ref=e569]:
                - listitem [ref=e570]:
                  - link " 首頁" [ref=e571] [cursor=pointer]:
                    - /url: /
                    - generic [ref=e572]: 
                    - text: 首頁
                - listitem [ref=e573]:
                  - link " 總經" [ref=e574] [cursor=pointer]:
                    - /url: /macro
                    - generic [ref=e575]: 
                    - text: 總經
                - listitem [ref=e576]:
                  - link "全球" [ref=e577] [cursor=pointer]:
                    - /url: /macro
                    - text: 全球
                - listitem [ref=e579]:
                  - link "國家數據中心" [ref=e580] [cursor=pointer]:
                    - /url: /cross-country-database
                    - text: 國家數據中心
                - listitem [ref=e582]:
                  - link "美國" [ref=e583] [cursor=pointer]:
                    - /url: /macro/us
                    - text: 美國
                - listitem [ref=e585]:
                  - link "台灣" [ref=e586] [cursor=pointer]:
                    - /url: /macro/tw
                    - text: 台灣
                - listitem [ref=e588]:
                  - link "中國" [ref=e589] [cursor=pointer]:
                    - /url: /macro/cn
                    - text: 中國
                - listitem [ref=e591]:
                  - link "歐洲" [ref=e592] [cursor=pointer]:
                    - /url: /macro/eu
                    - text: 歐洲
                - listitem [ref=e594]:
                  - link "日本" [ref=e595] [cursor=pointer]:
                    - /url: /macro/jp
                    - text: 日本
                - listitem [ref=e597]:
                  - link "東南亞" [ref=e598] [cursor=pointer]:
                    - /url: /macro/an
                    - text: 東南亞
                - listitem [ref=e600]:
                  - link "新興市場" [ref=e601] [cursor=pointer]:
                    - /url: /macro/em
                    - text: 新興市場
            - generic [ref=e603]:
              - heading "產業" [level=6] [ref=e604]
              - list [ref=e605]:
                - listitem [ref=e606]:
                  - link " 產業決策平台" [ref=e607] [cursor=pointer]:
                    - /url: /industry-intelligence-hub
                    - generic [ref=e608]: 
                    - text: 產業決策平台
                - listitem [ref=e609]:
                  - link " 美股財報資料庫" [ref=e610] [cursor=pointer]:
                    - /url: /stocks/screener
                    - generic [ref=e611]: 
                    - text: 美股財報資料庫
                - listitem [ref=e612]:
                  - link " 台灣產業專區" [ref=e613] [cursor=pointer]:
                    - /url: /sectors
                    - generic [ref=e614]: 
                    - text: 台灣產業專區
            - generic [ref=e615]:
              - heading "圖表與行情" [level=6] [ref=e616]
              - list [ref=e617]:
                - listitem [ref=e618]:
                  - link " 操盤人必看" [ref=e619] [cursor=pointer]:
                    - /url: /trader-insights
                    - generic [ref=e620]: 
                    - text: 操盤人必看
                - listitem [ref=e621]:
                  - link " 外匯觀測站" [ref=e622] [cursor=pointer]:
                    - /url: /forex
                    - generic [ref=e623]: 
                    - text: 外匯觀測站
                - listitem [ref=e624]:
                  - link " 股市觀測站" [ref=e625] [cursor=pointer]:
                    - /url: /stocks
                    - generic [ref=e626]: 
                    - text: 股市觀測站
                - listitem [ref=e627]:
                  - link " ETF觀測站" [ref=e628] [cursor=pointer]:
                    - /url: /etf
                    - generic [ref=e629]: 
                    - text: ETF觀測站
                - listitem [ref=e630]:
                  - link " 原物料觀測站" [ref=e631] [cursor=pointer]:
                    - /url: /commodities
                    - generic [ref=e632]: 
                    - text: 原物料觀測站
                - listitem [ref=e633]:
                  - link " 債券觀測站" [ref=e634] [cursor=pointer]:
                    - /url: /bonds
                    - generic [ref=e635]: 
                    - text: 債券觀測站
                - listitem [ref=e636]:
                  - link " 加密貨幣觀測站" [ref=e637] [cursor=pointer]:
                    - /url: /crypto
                    - generic [ref=e638]: 
                    - text: 加密貨幣觀測站
                - listitem [ref=e639]:
                  - link " 波動率觀測站" [ref=e640] [cursor=pointer]:
                    - /url: /volatility
                    - generic [ref=e641]: 
                    - text: 波動率觀測站
                - listitem [ref=e642]:
                  - link " 主權債違約觀測站" [ref=e643] [cursor=pointer]:
                    - /url: /cds
                    - generic [ref=e644]: 
                    - text: 主權債違約觀測站
            - generic [ref=e645]:
              - heading "專區" [level=6] [ref=e646]
              - list [ref=e647]:
                - listitem [ref=e648]:
                  - link " ETF 專區" [ref=e649] [cursor=pointer]:
                    - /url: /etf/us/screener
                    - generic [ref=e650]: 
                    - text: ETF 專區
                - listitem [ref=e651]:
                  - link " 川普專區" [ref=e652] [cursor=pointer]:
                    - /url: /potus-47-donald-trump
                    - generic [ref=e653]: 
                    - text: 川普專區
                - listitem [ref=e654]:
                  - link " 央行專區" [ref=e655] [cursor=pointer]:
                    - /url: /central_bank/overview
                    - generic [ref=e656]: 
                    - text: 央行專區
                - listitem [ref=e657]:
                  - link " 原物料專區" [ref=e658] [cursor=pointer]:
                    - /url: /commodities/overview
                    - generic [ref=e659]: 
                    - text: 原物料專區
                - listitem [ref=e660]:
                  - link " 13F機構持倉" [ref=e661] [cursor=pointer]:
                    - /url: /13f
                    - generic [ref=e662]: 
                    - text: 13F機構持倉
                - listitem [ref=e663]:
                  - link " 大額交易人持倉" [ref=e664] [cursor=pointer]:
                    - /url: /cot-flow
                    - generic [ref=e665]: 
                    - text: 大額交易人持倉
                - listitem [ref=e666]:
                  - link " 時間軸" [ref=e667] [cursor=pointer]:
                    - /url: /time_line
                    - generic [ref=e668]: 
                    - text: 時間軸
                - listitem [ref=e669]:
                  - link " 動態圖表" [ref=e670] [cursor=pointer]:
                    - /url: /dynamic_chart
                    - generic [ref=e671]: 
                    - text: 動態圖表
            - generic [ref=e672]:
              - heading "分析" [level=6] [ref=e673]
              - list [ref=e674]:
                - listitem [ref=e675]:
                  - link " MM獨家報告" [ref=e676] [cursor=pointer]:
                    - /url: /mails/monthly_report
                    - generic [ref=e677]: 
                    - text: MM獨家報告
                - listitem [ref=e678]:
                  - link " MM短評" [ref=e679] [cursor=pointer]:
                    - /url: /quickie
                    - generic [ref=e680]: 
                    - text: MM短評
                - listitem [ref=e681]:
                  - link " 關鍵圖表" [ref=e682] [cursor=pointer]:
                    - /url: /spotlights
                    - generic [ref=e683]: 
                    - text: 關鍵圖表
                - listitem [ref=e684]:
                  - link " 部落格" [ref=e685] [cursor=pointer]:
                    - /url: /blog
                    - generic [ref=e686]: 
                    - text: 部落格
                - listitem [ref=e687]:
                  - link " 部落格 RSS" [ref=e688] [cursor=pointer]:
                    - /url: /feed
                    - generic [ref=e689]: 
                    - text: 部落格 RSS
            - generic [ref=e690]:
              - heading "工具" [level=6] [ref=e691]
              - list [ref=e692]:
                - listitem [ref=e693]:
                  - link " 財經行事曆" [ref=e694] [cursor=pointer]:
                    - /url: /calendar
                    - generic [ref=e695]: 
                    - text: 財經行事曆
                - listitem [ref=e696]:
                  - link " 研究工具箱" [ref=e697] [cursor=pointer]:
                    - /url: /toolbox/chart-builder/line
                    - generic [ref=e698]: 
                    - text: 研究工具箱
                - listitem [ref=e699]:
                  - link " 數據" [ref=e700] [cursor=pointer]:
                    - /url: /series
                    - generic [ref=e701]: 
                    - text: 數據
              - heading "學院與社群" [level=6] [ref=e702]
              - list [ref=e703]:
                - listitem [ref=e704]:
                  - link " MM總經線上學院" [ref=e705] [cursor=pointer]:
                    - /url: /video
                    - generic [ref=e706]: 
                    - text: MM總經線上學院
                - listitem [ref=e707]:
                  - link " MM Podcast 頻道" [ref=e708] [cursor=pointer]:
                    - /url: https://podcasts.apple.com/tw/podcast/macromicro-%E8%B2%A1%E7%B6%93m%E5%B9%B3%E6%96%B9/id1522682178
                    - generic [ref=e709]: 
                    - text: MM Podcast 頻道
                - listitem [ref=e710]:
                  - link " 用戶觀點 Public" [ref=e711] [cursor=pointer]:
                    - /url: /shared_chart
                    - generic [ref=e712]: 
                    - text: 用戶觀點
                    - generic [ref=e713]: Public
            - generic [ref=e714]:
              - heading "鄧白氏 NEW" [level=6] [ref=e715]:
                - text: 鄧白氏
                - generic [ref=e716]: NEW
              - list [ref=e717]:
                - listitem [ref=e718]:
                  - link " 企業尊榮版領航方案" [ref=e719] [cursor=pointer]:
                    - /url: /macromicro-dun-and-bradstreet-globalview
                    - generic [ref=e720]: 
                    - text: 企業尊榮版領航方案
                - listitem [ref=e721]:
                  - link " D&B GlobalView 數據專區" [ref=e722] [cursor=pointer]:
                    - /url: /dnb/dun-and-bradstreet-globalview
                    - generic [ref=e723]: 
                    - text: D&B GlobalView 數據專區
                - listitem [ref=e724]:
                  - link " 全球企業樂觀洞察" [ref=e725] [cursor=pointer]:
                    - /url: /dnb/global-business-optimism-insights
                    - generic [ref=e726]: 
                    - text: 全球企業樂觀洞察
                - listitem [ref=e727]:
                  - link " 國家風險評級" [ref=e728] [cursor=pointer]:
                    - /url: /dnb/country-risk-ratings
                    - generic [ref=e729]: 
                    - text: 國家風險評級
                - listitem [ref=e730]:
                  - link " 產業風險評級" [ref=e731] [cursor=pointer]:
                    - /url: /dnb/sector-risk-ratings
                    - generic [ref=e732]: 
                    - text: 產業風險評級
                - listitem [ref=e733]:
                  - link " 國家 ESG 評級" [ref=e734] [cursor=pointer]:
                    - /url: /dnb/country-esg-risk-ratings
                    - generic [ref=e735]: 
                    - text: 國家 ESG 評級
                - listitem [ref=e736]:
                  - link " 企業營收與員工人數推估模型" [ref=e737] [cursor=pointer]:
                    - /url: /dnb/global-sales-employee-models
                    - generic [ref=e738]: 
                    - text: 企業營收與員工人數推估模型
                - listitem [ref=e739]:
                  - link " 企業數據下載" [ref=e740] [cursor=pointer]:
                    - /url: /dnb/corporate-data
                    - generic [ref=e741]: 
                    - text: 企業數據下載
            - generic [ref=e742]:
              - heading "更多" [level=6] [ref=e743]
              - list [ref=e744]:
                - listitem [ref=e745]:
                  - link " MM福利兌換" [ref=e746] [cursor=pointer]:
                    - /url: /user/mm-benefits
                    - generic [ref=e747]: 
                    - text: MM福利兌換
                - listitem [ref=e748]:
                  - link " 幫助中心" [ref=e749] [cursor=pointer]:
                    - /url: https://support.macromicro.me/hc/zh-tw
                    - generic [ref=e750]: 
                    - text: 幫助中心
                - listitem [ref=e751]:
                  - link " 新手教學" [ref=e752] [cursor=pointer]:
                    - /url: /teaching
                    - generic [ref=e753]: 
                    - text: 新手教學
                - listitem [ref=e754]:
                  - link " 關於我們" [ref=e755] [cursor=pointer]:
                    - /url: /about
                    - generic [ref=e756]: 
                    - text: 關於我們
                - listitem [ref=e757]:
                  - link " 聯絡我們" [ref=e758] [cursor=pointer]:
                    - /url: /contact-us
                    - generic [ref=e759]: 
                    - text: 聯絡我們
                - listitem [ref=e760]:
                  - link " 加入我們" [ref=e761] [cursor=pointer]:
                    - /url: /careers
                    - generic [ref=e762]: 
                    - text: 加入我們
                - listitem [ref=e763]:
                  - link " 訂閱方案" [ref=e764] [cursor=pointer]:
                    - /url: /subscribe
                    - generic [ref=e765]: 
                    - text: 訂閱方案
                - listitem [ref=e766]:
                  - link " 企業方案" [ref=e767] [cursor=pointer]:
                    - /url: /subscribe#enterprise
                    - generic [ref=e768]: 
                    - text: 企業方案
                - listitem [ref=e769]:
                  - link " 服務條款" [ref=e770] [cursor=pointer]:
                    - /url: /terms
                    - generic [ref=e771]: 
                    - text: 服務條款
                - listitem [ref=e772]:
                  - link " Facebook 專頁" [ref=e773] [cursor=pointer]:
                    - /url: https://www.facebook.com/macromicro.me/
                    - generic [ref=e774]: 
                    - text: Facebook 專頁
                - listitem [ref=e775]:
                  - link " LINE 官方帳號" [ref=e776] [cursor=pointer]:
                    - /url: https://line.me/ti/p/%40jml8635s
                    - generic [ref=e777]: 
                    - text: LINE 官方帳號
                - listitem [ref=e778]:
                  - link " YouTube" [ref=e779] [cursor=pointer]:
                    - /url: https://www.youtube.com/channel/UC6LU7FUBvbFCh_cQasrHZ_Q
                    - generic [ref=e780]: 
                    - text: YouTube
                - listitem [ref=e781]:
                  - link " Instagram" [ref=e782] [cursor=pointer]:
                    - /url: https://www.instagram.com/macromicro.me/
                    - generic [ref=e783]: 
                    - text: Instagram
          - generic [ref=e784]:
            - paragraph [ref=e785]: Copyright © 2026 MacroMicro
            - paragraph [ref=e786]: 網站內提供之數據資料、分析工具、網誌內容僅供使用者作為參考，實際數據以官方公佈資料為準。任何交易行為須自行判斷並承擔風險，本網站不負擔盈虧之法律責任。
            - paragraph [ref=e787]: 歡迎分享本網站提供之資訊連結，如需轉載內容務必經由本公司同意。
            - generic [ref=e788]:
              - link "繁體中文":
                - /url: //www.macromicro.me/
              - link "简体中文" [ref=e789] [cursor=pointer]:
                - /url: //sc.macromicro.me/
              - link "English" [ref=e790] [cursor=pointer]:
                - /url: //en.macromicro.me/
    - text:                                                                           
  - generic:
    - button "":
      - generic: 
    - button " 幫 助 中 心":
      - generic:
        - generic: 
        - generic:
          - text: 幫
          - text: 助
          - text: 中
          - text: 心
    - button "":
      - generic:
        - generic: 
  - text: 